version: "3.3"
services:

    #######################################################
    #  Rabbitmq
    #######################################################
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - shop

    #######################################################
    #  Postgress
    #######################################################
  postgres:
   image: postgres:latest
   container_name: postgres
   restart: unless-stopped
   ports:
     - '5432:5432'
   environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
   command:
     - "postgres"
     - "-c"
     - "wal_level=logical"
     - "-c"
     - "max_prepared_transactions=10"
   networks:
     - shop
     
    #######################################################
    #  Jaeger
    #######################################################
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one
    restart: unless-stopped
    networks:
      - shop
    ports:
      - 5775:5775/udp
      - 5778:5778
      - 6831:6831/udp
      - 6832:6832/udp
      - 9411:9411
      - 14268:14268
      - 16686:16686
      

networks:
  shop:




